import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const font_inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${font_inter.className} antialiased dark`}>{children}</body>
    </html>
  );
}
